FROM python:3.9-slim-bullseye
WORKDIR /app
COPY requirements.txt .
COPY devopsbot.py .
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /app/logs
RUN apt-get update && \
    apt-get install -y openssh-server
CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

